name: Zola

on:
  # Triggers the workflow on push or pull request events but only for the source branch
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v1
        with:
          ref: source
        
      - name: Download Zola Release
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: getzola/zola 
          tag: 'v0.14.1'
          file: zola-v0.14.1-x86_64-unknown-linux-gnu.tar.gz

      - name: Extract Zola Binary
        run: tar -xzf zola-v0.14.1-x86_64-unknown-linux-gnu.tar.gz

      - name: Build
        run: |
          ./zola build
          # Remove zola binary and downloads before deploy
          rm -f zola*
          
      - name: Copy build to main branch
        uses: planetoftheweb/copy-to-branches@v1.1
        with:
          # The committer's email address
          email: ${{ github.actor }}@gmail.com
        env:
          key: source
          branches: main
